version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - gep13
  assignees:
  - gep13
  labels:
  - dependabot
  ignore:
  - dependency-name: "@types/vscode"
    versions:
    - "> 1.50.0"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.8
    - 2.5.9
  - dependency-name: adm-zip
    versions:
    - 0.5.2
    - 0.5.3
    - 0.5.4
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: vscode-test
    versions:
    - 1.5.0
    - 1.5.1
